export default {
  MSG_TYPE: {
    TEXT: 1,
    IMAGE: 3,
    VOICE: 34,
    SHARE_CARD: 42,
    VIDEO: 43,
    CUSTOM_EXPRESSION: 47,
    LOCATION: 48,
    URL: 49,
    CALLING: 50,
    CHATROOM_CALLING: 64,
    REAL_TIME_POSITION: -1879048186,
    READ_ENVELOPES: 436207665,
    ACCOUNT_TRANSFER: 419430449,
    SYSTEM: 10000,
    JX_SYS_TEXT: 90000,
    MEMBER_CHANGE: 570425393,
    SYSTEM_MONEY: -10001,
    TIME_DIVIDER: -12346789,
    TEXT_WITH_AT: 1,
    TRANSFERKF: 50001,
    IMAGE_GIF: 1048625,
    COUPON: 452984881
  },
  CLIENT: "kefu-client",
  EVENT_BUS_EVENTS: {
    NEW_MESSAGE: "NewMessage",
    SEND_MESSAGE_RESP: "SendMessageResp",
    SEND_MESSAGE_UPDATE: "SendMessageUpdate",
    SEND_MESSAGE_RESULT: "SendMessageResult",
    FRIEND_INFO_CHANGED: "FriendInfoChanged",
    CHATROOM_INFO_CHANGED: "ChatroomInfoChanged",
    SESSION_LOST: "SessionLost",
    REPLY_SEND: "ReplySend",
    REPLY_REF: "ReplyRef",
    CHAT_TARGET_NEW_MESSAGE: "ChatTargetNewMessage",
    CHAT_TARGET_CHANGED: "ChatTargetChanged",
    VOICE_PLAYER_PAUSED: "VoicePlayerPaused",
    OPEN_HISTORY_MESSAGES: "OpenHistoryMessages",
    WECHAT_ACCOUNTS_ALIVE_STATUS: "WechatAccountsAliveStatus",
    VIEW_IMAGE: "ViewImage",
    OPEN_TOOLS: "Opentools",
    STATRT_TRANSLATE_VOICE: "startTranslateVoice",
    VOICE_TO_TEXT_RESULT: "voiceToTextResult",
    WECHAT_ACCOUNTID_FOLLOWED_INIT: "wechatAccountIdFollowedInit",
    SELECT_WECHAT_ACCOUNT_AND_LISTTABKEY: "SelectWechatAccountAndListTabKey",
    NEW_FRIEND_ASK: "newFriendAsk",
    OEM_GOT: "oemGot",
    TRANS_MONEY_RECEIVED: "transMoneyReceived",
    LUCKY_MONEY_OPENED: "luckyMoneyOpened",
    NEW_MSG_ON_HIDDEN: "newMsgOnHidden",
    FETCH_MOMENT_RESULT: "fetchMomentResult",
    MESSAGE_RECALLED: "messageRecalled",
    DOWNLOAD_VIDEO_RESULT: "downloadVideoResult",
    QUOTE_CONTENT: "quoteContent",
    TRANSMIT_MESSAGE: "transmitMessage",
    AIKE_GOOD_RECOMMEND: "aikeGoodRecommend",
    CHATROOM_MEMBER_AT: "chatroomMemberAt",
    REFRESH_SENSITIVE_WORD: "RefreshSensitiveWord",
    SHOW_NOTIFY_MESSAGE: "ShowNotifyMessage",
    CHATROOM_OPERATE: "chatroomOperate",
    WECHATMOMENT_INFO: "wechatMomentInfo",
    MOMENT_NEW_FRIENDS: "momentNewFriends",
    WECHATMOMENT_IMGS_LIST: "wechatMomentImgsList",
    MOMENT_LOADMORE: "momentLoadMore",
    MOMENT_LOADMORE_FRIENDS: "momentLoadMoreFriends",
    MOMENT_MESSAGE: "momentMsg",
    VERIFYFRIENDREQUEST: "verifyFriendreQuestResp",
    VERIFYFRIENDRERESULT: "verifyFriendResult",
    SIGNALR_SIGN_SUCC: "signalrSignSucc",
    NEWSYSMESSAGE: "newSysMessage",
    CHECKWECHATALIVE: "checkWechatAlive",
    MOMENT_ONE: "momentOne",
    CLEAR_RECENT_UNREAD_MESSAGES_4_SIGNALR: "clearRecentUnReadMessage4SignalR",
    SYNC_UNREAD_MESSAGES_4_WX: "syncUnReadMessage4WX",
    DOWN_TOKEN_LOSS: "downTokenLoss",
    GROUP_CHANGE: "updateGroupChange",
    GROUP_INFO_CHANGE: "updateGroupInfoChange",
    SYS_CONFIG_CHANGE: "updateSensitiveWordsList",
    TRANS_MONEY_RESULT: "transMoneyResult",
    SEND_FAILD_REPORT: "sendFaildReport",
    EDITAREAFOCUS: "editareafocus",
    LUCKY_MONEY_OPEN_RESULT: "luckyMoneyOpenResult",
    CALC_COMPLETE_RATE: "calcCompleteRate",
    CLUSTER_QR_CODE: "clusterQRCode",
    BIND_NOTICE: "reloadOrder",
    STAND_BACK_ORDER: "standBackOrder",
    CHECK_AUTO_REPLY: "checkAutoReply",
    UPDATE_QUICK_REPLY: "updateQuickReply",
    UPDATE_ANNOUNCEMENT: "updateAnnouncement",
    FRIEND_INFO_CHANGED_4_TAG: "friendInfoChanged4Tag",
    PERSONAL_SUB_DATA_UPDATE: "personalSubDataUpdate",
    ADD_MEMBERLIST_FRIEND: "addMemberlistFriend",
    RECONNECT_REMINDER: "reconnectReminder",
    UPLOAD_GROUP_TAG: "uploadGroupTag"
  },
  FIELD_TYPE: {
    NUMBER: 1,
    TEXT: 2,
    MULTI_TEXT: 4,
    DATE: 8,
    DATE_TIME: 16,
    RADIO: 32,
    CHECKBOX: 64
  },
  FRIEND_TRANSFER_SCOPE: {
    CURRENT_DEPARTMENT: "CurrentDepartment",
    IN_COMPANY: "InCompany"
  },
  SIGNALR_ERROR_CODE: {
    DataError: "2001",
    SystemError: "2002",
    DatabaseError: "3001",
    LoginInvalid: "4001",
    NoSign: "105001",
    SSOUnLogin: "107002"
  },
  SEND_STATUS: {
    tobeSend: 1,
    sending: 2,
    success: 4,
    fail: 8,
    recall: 16,
    delete: 32
  },
  IS_SEND: { self: 1, others: 0 },
  CHAT_TARGET_TYPE: { chatroom: 2, friend: 1 },
  TRANSACTION_PAYSUBTYPE: { sentout: 1, collection: 3, refund: 4 },
  ONLINE_STATUS: { online: 1, offline: 2, leave: 3 },
  BINDING_STATUS: { unbind: 1, bind: 2, cancelbind: 4 },
  BINDING_TYPE: { account: 1, mobile: 2, orderno: 3 },
  PLATFORMTYPE: {
    TAOBAO: "1",
    JD: "2",
    PINGDDUODUO: "4",
    YOUZAN: "5",
    SELF: "6"
  },
  CHANGETYPE: { ADD: 1, MODIFY: 2, REMOVE: 3, MEMBERCHANGE: 4, QUIT: 5 },
  ATTACHTYPE: {
    music: 3,
    video: 4,
    link: 5,
    file: 6,
    game: 7,
    favorite: 19,
    routine: 33,
    "open-routine": 36
  },
  TRADE_STATUS: {
    tobeconfirmed: 1,
    confirming: 2,
    confirmed: 4,
    failure: 8,
    overdue: 16
  },
  FRIEND_STATUS: {
    waitforpass: 1,
    haspass: 2,
    blacklist: 4,
    none: 8,
    delete: 16
  },
  TRANSACTION_STATUS: { initial: 0, inprogress: 1, complete: 2 },
  SENSITIVETYPE: { stop: 1, warn: 2 },
  ISRETURNNAME: { setup: 1, none: 2 },
  PICTURE_QUALITY_ATTACHTYPE: {
    empty: 1,
    bad: 2,
    medium: 4,
    good: 8,
    high: 16
  },
  AT_TYPE: { all: "announcement@all" },
  FILE_EXTS: {
    txt: "txt",
    ppt: "ppt",
    pptx: "pptx",
    doc: "doc",
    docx: "docx",
    xls: "xls",
    xlsx: "xlsx",
    pdf: "pdf",
    zip: "zip",
    rar: "rar",
    rar4: "rar4",
    image: "image"
  },
  APPLET_TYPE: { noCover: 1, isCover: 2 },
  MAX_FILE_SIZE: {
    FILE: { size: 25 * 1024 * 1024, label: "25MB" },
    GIF: { size: 3 * 1024 * 1024, label: "3MB" },
    IMAGE: { size: 25 * 1024 * 1024, label: "25MB" },
    VIDEO: { size: 30 * 1024 * 1024, label: "30MB" }
  },
  MOMENT_TYPE: { oneself: 1, friend: 2, newest: 3 },
  MOMENT_INFO_TYPE: {
    TEXT: 1,
    IMAGE: 2,
    VIDEO: 4,
    LINK: 8,
    SHARE_MUSIC: 16,
    SHARE_VIDEO: 32
  },
  ALLOT_TYPE: {
    ASSIGNOR_TYPE: { chatroom: 2, friend: 1 },
    CHANGE_TYPE: { add: 1, remove: 3 }
  },
  LIKE_COMMENT: { like: 1, comment: 2 },
  VISIBLE_CATEGORY: { ALL: 1, PRIVATE: 2, SPECIFED: 4, SHIELDING: 8 },
  DISTURB: { open: 1, guan: 2 },
  SEND_FRIEND_FILE_STYLE: {
    IMAGE: { size: 15 * 1024 * 1024, sizeLabel: "15MB" },
    VIDEO: {
      size: 25 * 1024 * 1024,
      sizeLabel: "25MB",
      duration: 15,
      durationLabel: "15秒"
    },
    COVER: { size: 1 * 1024 * 1024, sizeLabel: "1MB" }
  },
  FREAUENTLY: {
    MAX_RREQUENTLY_COUNT: 100,
    INTERVAL_TIME: 60000,
    BAN_TIME: 300000
  }
};